player_stat_columns = {
    "passing": {
        "selections": [
            "SUM(match_pass_completions)",
            "SUM(match_pass_attempts)",
            "SUM(match_pass_yards)",
            "SUM(match_pass_tds)",
            "SUM(match_pass_ints)",
            "SUM(match_pass_sacks)",
            "(CAST(SUM(match_pass_completions) AS DECIMAL)/SUM(match_pass_attempts))*100",
            "(CAST(SUM(match_pass_yards) AS DECIMAL)/SUM(match_pass_attempts))",
        ],
        "criteria": "match_pass_attempts > 0",
        "categories": [
            "first_name",
            "last_name",
            "position",
            "team",
            "completions",
            "attempts",
            "yards",
            "tds",
            "interceptions",
            "sacks",
            "completion_pct",
            "yards_per",
        ],
    },
    "rushing": {
        "selections": [
            "SUM(match_rush_attempts)",
            "SUM(match_rush_yards)",
            "SUM(match_rush_tds)",
            "SUM(match_fumble)",
        ],
        "criteria": "match_rush_attempts > 0",
        "categories": [
            "first_name",
            "last_name",
            "position",
            "team",
            "rush_attempts",
            "rush_yards",
            "rush_tds",
            "fumbles",
        ],
    },
    "receiving": {
        "selections": [
            "SUM(match_receiving_receptions)",
            "SUM(match_receiving_yards)",
            "CAST(SUM(match_receiving_yards) AS DECIMAL)/SUM(match_receiving_receptions)",
            "SUM(match_receiving_tds)",
            "SUM(match_receiving_targets)",
            "SUM(match_fumble)",
        ],
        "criteria": "match_receiving_receptions > 0",
        "categories": [
            "first_name",
            "last_name",
            "position",
            "team",
            "receptions",
            "receiving_yards",
            "receiving_yards_per_attempt",
            "receiving_tds",
            "receiving_targets",
            "fumbles",
        ],
    },
    "defense": {
        "selections": [
            "SUM(match_defense_tackles)",
            "SUM(match_defense_sacks)",
            "SUM(match_defense_int)",
            "SUM(match_defense_int_yards)",
            "SUM(match_defense_deflections)",
            "SUM(match_defense_tackles_for_loss)",
        ],
        "criteria": "match_defense_tackles > 0",
        "categories": [
            "first_name",
            "last_name",
            "position",
            "team",
            "tackles",
            "sacks",
            "interceptions",
            "interception_yards",
            "deflections",
            "tackles_for_loss",
        ],
    },
    "kicking": {
        "selections": [
            "SUM(match_kick_fg_made)",
            "SUM(match_kick_fg_attempts)",
            "MAX(match_kick_fg_long)",
            "(CAST(SUM(match_kick_fg_made) AS DECIMAL)/NULLIF(SUM(match_kick_fg_attempts), 0))",
            "SUM(match_kick_xp_made)",
            "SUM(match_kick_xp_attempts)",
            "(CAST(SUM(match_kick_xp_made) AS DECIMAL)/NULLIF(SUM(match_kick_xp_attempts), 0))",
        ],
        "criteria": "match_kick_xp_attempts > 0",
        "categories": [
            "first_name",
            "last_name",
            "position",
            "team",
            "fg_made",
            "fg_attempts",
            "fg_long",
            "fg_percentage",
            "xp_made",
            "xp_attempts",
            "xp_percentage",
        ],
    },
    "punting": {
        "selections": [
            "CAST(SUM(match_punt_gross_yards) AS DECIMAL)/SUM(match_punt_count)",
            "SUM(match_punt_net_yards)",
            "CAST(SUM(match_punt_net_yards) AS DECIMAL)/SUM(match_punt_count)",
            "SUM(match_punt_count)",
            "MAX(match_punt_long)",
            "SUM(match_punt_gross_yards)",
            "SUM(match_punt_touchbacks)",
        ],
        "criteria": "match_punt_count > 0",
        "categories": [
            "first_name",
            "last_name",
            "position",
            "team",
            "gross_yards_per_punt",
            "net_yards",
            "net_yards_per_punt",
            "punt_count",
            "long",
            "gross_yards",
            "touchbacks",
        ],
    },
    "kick_return": {
        "selections": [
            "CAST(SUM(match_kick_return_yards) AS DECIMAL)/NULLIF(SUM(match_kick_return_count), 0)",
            "SUM(match_kick_return_count)",
            "SUM(match_kick_return_yards)",
            "SUM(match_kick_return_tds)",
            "MAX(match_kick_return_long)",
        ],
        "criteria": "match_kick_return_count > 0",
        "categories": [
            "first_name",
            "last_name",
            "position",
            "team",
            "yards_per_return",
            "count",
            "yards",
            "tds",
            "long",
        ],
    },
    "punt_return": {
        "selections": [
            "CAST(SUM(match_punt_return_yards) AS DECIMAL)/NULLIF(SUM(match_punt_return_count), 0)",
            "SUM(match_punt_return_count)",
            "SUM(match_punt_return_yards)",
            "SUM(match_punt_return_tds)",
            "MAX(match_punt_return_long)",
        ],
        "criteria": "match_punt_return_count > 0",
        "categories": [
            "first_name",
            "last_name",
            "position",
            "team",
            "yards_per_return",
            "count",
            "yards",
            "tds",
            "long",
        ],
    },
}
